Repository jenkinsci/customizable-header-plugin, pull requests merged in 2023-11, with the labels that each got.

#44 system messages
  README.md
  docs/pics/system-message.png
  src/main/java/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration.java
  src/main/java/io/jenkins/plugins/customizable_header/SystemMessage.java
  src/main/java/io/jenkins/plugins/customizable_header/headers/LogoHeader.java
  src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration/config.jelly
  src/main/resources/io/jenkins/plugins/customizable_header/HeaderRootAction/theme.jelly
  src/main/resources/io/jenkins/plugins/customizable_header/SystemMessage/config.jelly
  src/main/resources/io/jenkins/plugins/customizable_header/SystemMessage/help-message.html
  src/main/resources/io/jenkins/plugins/customizable_header/headers/LogoHeader/headerContent.jelly
Labels: enhancement

#49 add a page decorator to preload css
  src/main/java/io/jenkins/plugins/customizable_header/CustomHeaderDecorator.java
  src/main/java/io/jenkins/plugins/customizable_header/headers/LogoHeader.java
  src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderDecorator/header.jelly
  src/main/resources/io/jenkins/plugins/customizable_header/headers/LogoHeader/headerContent.jelly
Labels: bug

#15 Move configuration to appearance page
  pom.xml
  src/main/java/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration.java
Labels: enhancement, breaking

#53 Some minor styling changes and fixes to make the header more compact
  src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration/config.jelly
  src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration/help-thinHeader.html
  src/main/resources/io/jenkins/plugins/customizable_header/HeaderRootAction/theme.jelly
Labels: enhancement
