Repository jenkinsci/customizable-header-plugin, pull requests merged in 2025-01, with the labels that each got.

#170 fix NPE when UserHeader not found
  src/main/java/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration.java
Labels: bug

#171 fix yarn.lock
  yarn.lock
Labels: dependencies

#172 avoid a leading separator
  src/main/java/io/jenkins/plugins/customizable_header/HeaderRootAction.java
  src/main/resources/io/jenkins/plugins/customizable_header/logo/Symbol/help-symbol.html
Labels: bug

#174 use ionicons-api as default plugin for links as well
  src/main/java/io/jenkins/plugins/customizable_header/AppNavLink.java
Labels: bug

#178 Use `jenkins.baseline` to reduce bom update mistakes
  pom.xml
Labels: chore

#184 Use global MarkupFormatter for headers and system message
  README.md
  pom.xml
  src/main/java/io/jenkins/plugins/customizable_header/SystemMessage.java
  src/main/java/io/jenkins/plugins/customizable_header/headers/LogoHeader.java
  src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration/config.jelly
  src/main/resources/io/jenkins/plugins/customizable_header/CustomHeaderConfiguration/help-title.html
  src/main/webapp/help-systemMessage.html
  src/test/java/io/jenkins/plugins/customizable_header/SystemMessageTest.java
  src/test/java/io/jenkins/plugins/customizable_header/headers/AbstractLogoHeaderTest.java
  src/test/java/io/jenkins/plugins/customizable_header/headers/ContextAwareHeaderTest.java
  src/test/java/io/jenkins/plugins/customizable_header/headers/LogoHeaderTest.java
Labels: breaking
